packages:
  - "packages/api/libraries/*"
  - "packages/api/tools/*"
  - "packages/backend/libraries/*"
  - "packages/backend/services/*"
  - "packages/backend/tools/*"
  - "packages/frontend/*"
  - "packages/tools/*"
