/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the generation script to regenerate this file.
 */

export type Types = Card;
export type Card = NormalCard;
export type NormalCard = ColoredCard & {
  number: CardNumber;
};
export type ColoredCard = BaseCard & {
  color: CardColor;
};
export type CardKind = "blank" | "draw" | "normal" | "reverse" | "skip" | "wild" | "wildDraw";
export type CardColor = "blue" | "green" | "red" | "yellow";
export type CardNumber = number;

export interface BaseCard {
  kind: CardKind;
}
