apiVersion: v1
kind: ConfigMap
metadata:
  name: game-service-config
  namespace: one-game
data:

  grafana.pyroscope-enabled: 'false'
  grafana.pyroscope-url: http://pyroscope:4040
  grafana.tracer-enabled: 'false'
  grafana.tracer-url: http://tempo:4317

  host: '0.0.0.0'

  port: '3002'

  redis.host: game-redis-cluster-leader
  redis.port: '6379'
