apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: rest-consumer-game-autoscaler
  name: rest-consumer-game-autoscaler
  namespace: one-game
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rest-consumer-game
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
