apiVersion: v1
kind: Secret
metadata:
  name: game-service-secret
  namespace: one-game
stringData:

  typeorm.config: |-
    {
      "synchronize": false,
      "type": "postgres",
      "url": "postgresql://your-user:your-password@game-db-cluster-rw:5432/game_service_db",
      "useUTC": true
    }

