services:
  db:
    image: postgres:16.6-alpine
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_service_db
    networks:
      - one_game
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

networks:
  one_game:
    external: true
    name: one_game_network

volumes:
  db:
    driver: local