import fs from 'node:fs/promises';
import path from 'node:path';
import { argv } from 'node:process';

import { readApiGraphqlSchemas } from '@cornie-js/api-graphql-schemas-provider';
import prettierConfig from '@cornie-js/backend-prettier-config';
import { CodegenConfig, executeCodegen } from '@graphql-codegen/cli';
import { Types } from '@graphql-codegen/plugin-helpers';
import { TypeScriptPluginConfig } from '@graphql-codegen/typescript';
import { TypeScriptResolversPluginConfig } from '@graphql-codegen/typescript-resolvers';
import prettier from 'prettier';

function arrayHasThreeElements<T>(value: T[]): value is [T, T, T, ...T[]] {
  const arrayMinimumLength: number = 3;

  return value.length >= arrayMinimumLength;
}

async function generateAllModels(destinationPath: string): Promise<void> {
  await fs.mkdir(path.dirname(destinationPath), { recursive: true });

  const plugindConfig: TypeScriptPluginConfig &
    TypeScriptResolversPluginConfig = {
    avoidOptionals: true,
    enumsAsTypes: true,
    resolverTypeWrapperSignature: 'Partial<T> | Promise<Partial<T>>',
    useIndexSignature: true,
  };

  /*
   * Consider https://the-guild.dev/graphql/codegen/plugins/typescript/typescript as reference
   * Consider https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers as refrence
   */
  const config: CodegenConfig = {
    generates: {
      [destinationPath]: {
        config: plugindConfig,
        plugins: ['typescript', 'typescript-resolvers'],
      },
    },
    schema: await readApiGraphqlSchemas(),
  };

  const fileOutputs: Types.FileOutput[] = await executeCodegen(config);

  const bannerContent: string = `/* eslint-disable */
/**
 * This file was automatically generated by @graphql-codegen/cli.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source graphql file,
 * and run the generation script to regenerate this file.
 */
`;

  await Promise.all(
    fileOutputs.map(async (fileOutput: Types.FileOutput): Promise<void> => {
      const sourceCode: string = bannerContent + fileOutput.content;
      const formattedSourceCode: string = await prettier.format(sourceCode, {
        ...prettierConfig,
        parser: 'typescript',
      });

      await fs.writeFile(fileOutput.filename, formattedSourceCode);
    }),
  );
}

void (async () => {
  if (arrayHasThreeElements(argv)) {
    const destinationFolder: string = argv[2];

    await generateAllModels(destinationFolder);
  } else {
    throw new Error('Invalid args!');
  }
})();
