apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: game-db-cluster
  namespace: one-game
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 2
  bootstrap:
    initdb:
      database: game_service_db
      owner: one-game-game-user
      secret:
        name: game-db-cluster-auth
  monitoring:
    enablePodMonitor: true
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: "256MB"

  resources:
    requests:
      memory: "1024Mi"
      cpu: 500m
    limits:
      memory: "1024Mi"
      cpu: 1

  storage:
    size: 1Gi
