#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

kubectl delete \
  -f "$SCRIPT_DIR"/grafana/grafana-dashboards.yaml \
  -f "$SCRIPT_DIR"/grafana/grafana-dashboards-config.yaml \
  -f "$SCRIPT_DIR"/grafana/grafana-datasources-config.yaml \
  -f "$SCRIPT_DIR"/grafana/grafana.yaml \
  -f "$SCRIPT_DIR"/prometheus/prometheus-config.yaml \
  -f "$SCRIPT_DIR"/prometheus/prometheus.yaml \
  -f "$SCRIPT_DIR"/tempo/tempo-config.yaml \
  -f "$SCRIPT_DIR"/tempo/tempo.yaml

kubectl delete -f "$SCRIPT_DIR"/namespace.yaml
