#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

kubectl delete \
  -f "$SCRIPT_DIR"/grafana/grafana-dashboards.yaml \
  -f "$SCRIPT_DIR"/grafana/grafana-dashboards-config.yaml \
  -f "$SCRIPT_DIR"/grafana/grafana-datasources-config.yaml \
  -f "$SCRIPT_DIR"/grafana/grafana.yaml \
  -f "$SCRIPT_DIR"/ingress.yaml \
  -f "$SCRIPT_DIR"/prometheus/prometheus-config.yaml \
  -f "$SCRIPT_DIR"/prometheus/prometheus.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/common/rest-api-config.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/common/rest-api.secret.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/db/db-cluster-auth.secret.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/db/db-cluster.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/game-service-config.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/game-service.secret.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/redis-cluster.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/game-service-migration.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/game-service/game-service.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/user-service/db/db-cluster-auth.secret.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/user-service/db/db-cluster.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/user-service/user-service-config.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/user-service/user-service.secret.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/user-service/user-service-migration.yaml \
  -f "$SCRIPT_DIR"/one-game-services/rest/user-service/user-service.yaml \
  -f "$SCRIPT_DIR"/tempo/tempo-config.yaml \
  -f "$SCRIPT_DIR"/tempo/tempo.yaml

kubectl delete -f "$SCRIPT_DIR"/namespace.yaml
