services:
  maildev:
    build:
      context: .
      dockerfile: docker/maildev.Dockerfile
    networks:
      - one_game
    ports:
      - 1080:1080
      - 1025:1025

networks:
  one_game:
    external: true
    name: one_game_network
