services:
  proxy:
    image: nginx:1.29.0-alpine
    environment:
      - USER_SERVICE_BASE_URL=${USER_SERVICE_BASE_URL}
      - GAME_SERVICE_BASE_URL=${GAME_SERVICE_BASE_URL}
    network_mode: 'host'
    ports:
      - '8000:8000'
    volumes:
      - ./templates:/etc/nginx/templates
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d/locations.conf:/etc/nginx/conf.d/locations.conf
      - ./config/conf.d/redirect-headers.conf:/etc/nginx/conf.d/redirect-headers.conf
      - ./ssl:/etc/ssl
