import { JwtAlgorithm } from '@cornie-js/backend-jwt';

export interface EnvironmentRaw extends Record<string, unknown> {
  ONE_JS_GAME_API_BACKEND_SERVICE_SECRET: string;
  ONE_JS_GAME_API_BASE_URL: string;
  ONE_JS_GAME_CONSUMER_HOST: string;
  ONE_JS_GAME_CONSUMER_PORT: number;
  ONE_JS_GAME_SERVICE_CORS_ORIGINS: string[];
  ONE_JS_GAME_SERVICE_GRAFANA_PYROSCOPE_ENABLED: boolean;
  ONE_JS_GAME_SERVICE_GRAFANA_PYROSCOPE_URL: string;
  ONE_JS_GAME_SERVICE_GRAFANA_TRACE_ENABLED: boolean;
  ONE_JS_GAME_SERVICE_GRAFANA_TRACE_URL: string;
  ONE_JS_GAME_SERVICE_HOST: string;
  ONE_JS_GAME_SERVICE_PORT: number;
  ONE_JS_GAME_SERVICE_PUB_SUB_REDIS_HOST: string;
  ONE_JS_GAME_SERVICE_PUB_SUB_REDIS_PORT: number;
  ONE_JS_GAME_SERVICE_TYPEORM_DATASOURCE_OPTIONS: Record<string, unknown>;
  ONE_JS_GAME_SERVICE_JWT_ALGORITHM: JwtAlgorithm;
  ONE_JS_GAME_SERVICE_JWT_AUDIENCE: string;
  ONE_JS_GAME_SERVICE_JWT_EXPIRATION_MS: number;
  ONE_JS_GAME_SERVICE_JWT_ISSUER: string;
  ONE_JS_GAME_SERVICE_JWT_PRIVATE_KEY: string;
  ONE_JS_GAME_SERVICE_JWT_PUBLIC_KEY: string;
  ONE_JS_GAME_SERVICE_PULSAR_GAME_TURN_SIGNAL_ENABLED: boolean | undefined;
  ONE_JS_GAME_SERVICE_PULSAR_GAME_TURN_SIGNAL_TOPIC_URL: string;
  ONE_JS_GAME_SERVICE_PULSAR_SERVICE_URL: string;
}
