networks:
  pulsar:
    driver: bridge
services:
  standalone:
    image: apachepulsar/pulsar:4.0.3
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf

volumes:
  pulsardata:
    name: pulsardata
  pulsarconf:
    name: pulsarconf
