/* eslint-disable */
/*
 * This file was automatically generated by the api json schema id enum generation.
 * script. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema files
 * and run the generation script to regenerate this file.
 */
export enum ApiSchemaId {
  ActiveGameSlotCardsV1 = 'https://onegame.schemas/api/v1/games/active-game-slot-cards.json',
  ActiveGameSlotV1 = 'https://onegame.schemas/api/v1/games/active-game-slot.json',
  ActiveGameStateV1 = 'https://onegame.schemas/api/v1/games/active-game-state.json',
  ActiveGameV1 = 'https://onegame.schemas/api/v1/games/active-game.json',
  AuthCreateQueryV1 = 'https://onegame.schemas/api/v1/auth/auth-create-query.json',
  AuthV1 = 'https://onegame.schemas/api/v1/auth/auth.json',
  CardArrayV1 = 'https://onegame.schemas/api/v1/cards/card-array.json',
  CardColorV1 = 'https://onegame.schemas/api/v1/cards/card-color.json',
  CardNumberV1 = 'https://onegame.schemas/api/v1/cards/card-number.json',
  CardV1 = 'https://onegame.schemas/api/v1/cards/card.json',
  DrawCardV1 = 'https://onegame.schemas/api/v1/cards/draw-card.json',
  ErrorV1 = 'https://onegame.schemas/api/v1/errors/error.json',
  GameCardSpecV1 = 'https://onegame.schemas/api/v1/games/game-card-spec.json',
  GameCreateQueryV1 = 'https://onegame.schemas/api/v1/games/game-create-query.json',
  GameDirectionV1 = 'https://onegame.schemas/api/v1/games/game-direction.json',
  GameIdPassTurnQueryV1 = 'https://onegame.schemas/api/v1/games/game-id-pass-turn-query.json',
  GameIdPlayCardsQueryV1 = 'https://onegame.schemas/api/v1/games/game-id-play-cards-query.json',
  GameIdSlotCreateQueryV1 = 'https://onegame.schemas/api/v1/games/game-id-slot-create-query.json',
  GameIdUpdateQueryV1 = 'https://onegame.schemas/api/v1/games/game-id-update-query.json',
  GameOptionsV1 = 'https://onegame.schemas/api/v1/games/game-options.json',
  GameSlotV1 = 'https://onegame.schemas/api/v1/games/game-slot.json',
  GameSpecV1 = 'https://onegame.schemas/api/v1/games/game-spec.json',
  GameV1 = 'https://onegame.schemas/api/v1/games/game.json',
  NonStartedGameSlotV1 = 'https://onegame.schemas/api/v1/games/non-started-game-slot.json',
  NonStartedGameStateV1 = 'https://onegame.schemas/api/v1/games/non-started-game-state.json',
  NonStartedGameV1 = 'https://onegame.schemas/api/v1/games/non-started-game.json',
  NormalCardV1 = 'https://onegame.schemas/api/v1/cards/normal-card.json',
  ReverseCardV1 = 'https://onegame.schemas/api/v1/cards/reverse-card.json',
  SkipCardV1 = 'https://onegame.schemas/api/v1/cards/skip-card.json',
  Types = 'https://onegame.schemas/api/types.json',
  TypesV1 = 'https://onegame.schemas/api/v1/types.json',
  UserCreateQueryV1 = 'https://onegame.schemas/api/v1/users/user-create-query.json',
  UserMeUpdateQueryV1 = 'https://onegame.schemas/api/v1/users/user-me-update-query.json',
  UserV1 = 'https://onegame.schemas/api/v1/users/user.json',
  WildCardV1 = 'https://onegame.schemas/api/v1/cards/wild-card.json',
  WildDraw4CardV1 = 'https://onegame.schemas/api/v1/cards/wild-draw-4-card.json',
}
