services:
  openapi_doc_server:
    image: swaggerapi/swagger-ui:v5.19.0
    environment:
      - SHOW_COMMON_EXTENSIONS=true
      - SWAGGER_JSON=/schemas/one-game.yaml
    networks:
      - one_game
    ports:
      - 8080:8080
    volumes:
      - ./node_modules/@cornie-js/api-openapi-schema/schemas/generated/one-game.yaml:/schemas/one-game.yaml

networks:
  one_game:
    external: true
    name: one_game_network
