apiVersion: v1
kind: Secret
metadata:
  name: rest-api-secret
  namespace: one-game
stringData:
  jwt.private: |-
    Your private key here

  jwt.public: |-
    Your public key here

  backend.service-secret: your-secret-here

  mail.user: user
  mail.password: password
