apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: one-game
stringData:

  mail.default-address: mail@example.com
  mail.host: localhost
  mail.password: password
  mail.port: '1025'
  mail.use-tls: 'false'
  mail.user: user

  typeorm.config: |-
    {
      "synchronize": false,
      "type": "postgres",
      "url": "postgresql://your-user:your-password@user-db-cluster-rw:5432/user_service_db",
      "useUTC": true
    }

