openapi: 3.1.0
info:
  title: One game API
  version: '1.0'
servers:
  - url: 'http://127.0.0.1:8000'
    description: Local development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /v1/auth:
    post:
      summary: Create an authorization token
      operationId: createAuth
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://onegame.schemas/api/v1/auth/auth-create-query.json'
      responses:
        '200':
          description: Authorization token created
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/auth/auth.json'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'

  /v1/games:
    post:
      summary: Create a game
      operationId: createGame
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://onegame.schemas/api/v1/games/game-create-query.json'
      responses:
        '200':
          description: Game created
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/games/non-started-game.json'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []

  /v1/games/{gameId}:
    get:
      summary: Get a game
      operationId: getGame
      parameters:
        - in: path
          name: gameId
          schema:
            type: string
          required: true
          description: Id of the game to get
      responses:
        '200':
          description: Game found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/games/game.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []
    patch:
      summary: Update a game
      operationId: updateGame
      parameters:
        - in: path
          name: gameId
          schema:
            type: string
          required: true
          description: Id of the game to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://onegame.schemas/api/v1/games/game-id-update-query.json'
      responses:
        '200':
          description: Game updated
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/games/game.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []

  /v1/games/{gameId}/slots:
    post:
      summary: Create a game slot
      operationId: createGameSlot
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://onegame.schemas/api/v1/games/game-id-slot-create-query.json'
      parameters:
        - in: path
          name: gameId
          schema:
            type: string
          required: true
          description: Id of the game containing the game slot to create
      responses:
        '200':
          description: Game slot created
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/games/game-slot.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '422':
          description: Unprocessable request
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []

  /v1/games/{gameId}/slots/{gameSlotIndex}/cards:
    get:
      summary: Get a game slot cards
      operationId: getGameSlotCards
      parameters:
        - in: path
          name: gameId
          schema:
            type: string
          required: true
          description: Id of the game containing the game slot to get
        - in: path
          name: gameSlotIndex
          schema:
            type: integer
          required: true
          description: Index of the game slot to get
      responses:
        '200':
          description: Game slot cards found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/games/active-game-slot-cards.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '422':
          description: Game slot cards not processable
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []


  /v1/users:
    post:
      summary: Create user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://onegame.schemas/api/v1/users/user-create-query.json'
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/users/user.json'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security: []

  /v1/users/me:
    get:
      summary: Get current user
      operationId: getUserMe
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/users/user.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '422':
          description: Unprocessable request
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []

  /v1/users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUser
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: Id of the user to get
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/users/user.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []
    patch:
      summary: Update a user by its id
      operationId: updateUser
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: Id of the user to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://onegame.schemas/api/v1/users/user-id-update-query.json'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/users/user.json'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://onegame.schemas/api/v1/errors/error.json'
      security:
        - bearerAuth: []
