name: run-e2e
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
jobs:
  run-e2e:
    name: Run E2E tests.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'refs/remotes/origin/master'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            pnpm-store-
        
      - name: Install dependencies
        run: pnpm install

      - name: Set proxy certificates
        run: mkdir ssl && openssl req -x509 -newkey rsa:4096 -keyout ssl/localhost.key.pem -out ssl/localhost.cert.pem -sha256 -days 3650 -nodes -subj "/CN=Dev proxy certificate"
        working-directory: ./packages/backend/tools/backend-dev-proxy

      - name: Start services with e2e config
        run: pnpm run start:e2e

      - name: Run e2e tests
        run: pnpm run test:e2e:js
        env:
          ONE_JS_TEST_E2E_DOT_ENV_PATH: e2e.env

      - name: Remove services with e2e config
        run: pnpm run close:e2e
